# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: searxng-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Random signing key. Store it in a 1Password item named "searxng".
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
  dataFrom:
    - extract:
        key: searxng
