---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  values:
    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/irqbalance
              tag: 1.9.5@sha256:0c4b233e7f3bf6753afc22082547ba7980b24e1cf7a9dabadfb149f4381232ee
            env:
              IRQBALANCE_BANNED_CPULIST: 12-19 # 12-19 are E-cores
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostIPC: true
      hostPID: true
    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
