templates:
  Chart Alpha:
    sort_title: ++++3.1_<<num>><<collection_name>>
    sync_mode: sync
    collection_order: alpha
  Best of:
    imdb_search:
      type: movie
      release.after: <<year>>-01-01
      release.before: <<year>>-12-31
      votes.gte: 25000
      sort_by: rating.desc
      limit: 50
    sort_title: ++++3.2_<<num>><<collection_name>>
    sync_mode: sync
    summary: Highest rated films of <<year>> on IMDb
    smart_label: audience_rating.desc

######################################################
#                     Best Of                        #
######################################################

collections:
  Best of 1980s:
    template: { name: Chart Alpha, num: 1.1 }
    imdb_search:
      type: movie
      release.after: 1980-01-01
      release.before: 1989-12-31
      votes.gte: 50000
      sort_by: rating.desc
      limit: 50
    summary: Best of 1980s
  Best of 1990s:
    template: { name: Chart Alpha, num: 1.2 }
    imdb_search:
      type: movie
      release.after: 1990-01-01
      release.before: 1999-12-31
      votes.gte: 50000
      sort_by: rating.desc
      limit: 50
    summary: Best of the 1990s
  Best of 2000s:
    template: { name: Chart Alpha, num: 1.3 }
    imdb_search:
      type: movie
      release.after: 2000-01-01
      release.before: 2009-12-31
      votes.gte: 50000
      sort_by: rating.desc
      limit: 50
    summary: Best of the 2000s
  Best of 2020:
    template: { name: Best of, year: 2020, num: 1.7 }
  Best of 2021:
    template: { name: Best of, year: 2021, num: 1.8 }
  Best of 2022:
    template: { name: Best of, year: 2022, num: 1.9 }
  Best of 2023:
    template: { name: Best of, year: 2023, num: 2.0 }
  Best of 2024:
    template: { name: Best of, year: 2024, num: 2.1 }
