---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csi-rbac.yaml
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
